# Generated by Django 4.2 on 2023-05-11 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.BigIntegerField(blank=True, unique=True)),
                ('name', models.CharField(max_length=400, unique=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.BigIntegerField(blank=True, unique=True)),
                ('username', models.CharField(max_length=400)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=320, unique=True)),
                ('dob', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.PROTECT, related_name='department', to='hrapp.department')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
